### ISSUE TITLE
关于坐标系、九段线和审图号

### ISSUE THREAD

**Issue by justoneee** [GaryBikini/ChinaAdminDivisonSHP#10]
1、坐标系，readme文件里面说
_`坐标系统：WGS 84（实际为[火星坐标系——GCJ-02](https://zh.wikipedia.org/wiki/%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E5%9C%B0%E7%90%86%E6%95%B0%E6%8D%AE%E9%99%90%E5%88%B6#GCJ-02)，见[参考资料](https://lbs.amap.com/api/javascript-api/guide/transform/convertfrom)；其基于WGS 1984，但在经纬度中加入了看似随机的偏移）`_
那这里面的坐标是直接把GCJ当做了WGS84，还是进行了坐标转换？

2、有没有什么办法可以在地图上加上九段线呢？

3、有没有审图号呢？

**Comment by GaryBikini** [comment]
1. 直接把GCJ当做了WGS84
