### ISSUE TITLE
黑龙江省省界好像不对

### ISSUE THREAD

**Issue by sunzhcas** [GaryBikini/ChinaAdminDivisonSHP#13]

**Comment by sunzhcas** [comment]
https://www.hlj.gov.cn/hlj/c108475/zjhlj.shtml
这个是黑龙江省官网提供的黑龙江省省界图（黑S（2022）37号），您可以看下

**Comment by GaryBikini** [comment]
@sunzhcas 谢谢你的细心发现；@liamxg 谢谢你的辅助沟通。本项目的数据是来自于高德Web服务API，所以是高德认为黑龙江应该有那块飞地。我本身对行政区划不是特别熟悉，因此顺便做了一些搜索，仅供参考。

![image](https://github.com/user-attachments/assets/d2ae7f65-f878-460b-a0d2-ca32583511c3)
![image](https://github.com/user-attachments/assets/49bef74d-ed05-4071-8e1e-12053c5e29cf)
![image](https://github.com/user-attachments/assets/f821c3a0-26ba-41a0-8656-d846d904ad43)
![image](https://github.com/user-attachments/assets/684152c7-547a-4088-9e79-11b37056f932)
