### ISSUE TITLE
您好，关于区域面积和长度的单位问题

### ISSUE THREAD

**Issue by bright1993ff66** [GaryBikini/ChinaAdminDivisonSHP#2]
您好！我想用下上海城区的shapefile，请问在这个表中：

![image](https://user-images.githubusercontent.com/29517359/98356103-0eaa7980-205e-11eb-8a0f-61d6969d34ac.png)

1. ```Shape_Area```的单位是什么呀？
2. 还有```Shape_Leng```是代表一个区的周长嘛？单位是千米嘛？

多谢！

**Comment by GaryBikini** [comment]
从属性表看，这不是我的数据。

**Comment by bright1993ff66** [comment]
@GaryBikini 哦哦抱歉！我自己搞错了，谢谢！
