### ISSUE TITLE
The map is accurate!!!

### ISSUE THREAD

**Issue by Tiramisu023** [GaryBikini/ChinaAdminDivisonSHP#4]
Yes, this map is accurate. 
It's consistent with  this official map [http://bzdt.ch.mnr.gov.cn/download.html?searchText=GS(2020)4619]
Thanks so much.

**Comment by GaryBikini** [comment]
You are welcome!

**Comment by Tiramisu023** [comment]
楼主您好，感谢您提供的地图。我又看了您发的这版地图，发现在大尺度上是没有问题的，但是在小尺度上，比如海南岛，放大之后，就缺乏细节。github 上有另外一版地图，地图放大之后，细节还是有的：https://github.com/dongli/china-shapefiles

**Comment by GaryBikini** [comment]
目前细节最多的就是这个了：
https://github.com/GaryBikini/ChinaAdminDivisonSHP/blob/master/1.%20%E5%9B%BD%E5%AE%B6%E8%8C%83%E5%9B%B4/4.%20%E7%B2%BE%E7%A1%AE%E5%88%B0District/districts.shp
