### ISSUE TITLE
您好，请问这个县级的中国全图可以支持由pyecharts 加载吗？

### ISSUE THREAD

**Issue by dongrixinyu** [GaryBikini/ChinaAdminDivisonSHP#6]

**Comment by GaryBikini** [comment]
我对pyecharts或echarts不熟悉。这里有一个echarts加载USA地图（https://s3-us-west-2.amazonaws.com/s.cdpn.io/95368/USA_geo.json）的示例，网址为https://codepen.io/geraldo/pen/zgvVre。回到本问题，则需要将本项目的数据格式（Shapefile）转换为GeoJSON格式，希望对你有帮助。
