### ISSUE TITLE
数据非常ok，没有南海的线，使用起来风险很大，这个有可能加上吗？

### ISSUE THREAD

**Issue by AmazureBUPT** [GaryBikini/ChinaAdminDivisonSHP#7]
或者有其他方式获取南海的线吗

**Comment by GaryBikini** [comment]
的确是一个问题，但是高德Web服务API中没有提供相关的调用接口，因此我暂时没有正规的数据来源。如果你使用高德地图JS API，它会以"图层"的形式加载国界线——”国家简易行政区图层 AMap.DistrictLayer.Country“。

**Comment by AkexStar** [comment]
@AmazureBUPT 
试试阿里这里的geojson格式的边界数据，带有十段线，也是高德的数据，坐标系是GCJ02

https://datav.aliyun.com/portal/school/atlas/area_selector

<img width="1439" alt="image" src="https://github.com/GaryBikini/ChinaAdminDivisonSHP/assets/55226358/8ca19da1-294d-468b-8c3e-2a2e34256064">

**Comment by GaryBikini** [comment]
多谢，我下载了该数据，不过其内部存储的不是经纬度，所以如何与现有数据整合还是一个问题

**Comment by GaryBikini** [comment]
@AmazureBUPT @AkexStar 你好，关于“南海的线”，天地图里有更为权威的数据，可参考https://mp.weixin.qq.com/s/tcoCyr-Zo0sn1pDHqDMcCw
