### ISSUE TITLE
引用DOI `10.5281/zenodo.7503181` 无法访问

### ISSUE THREAD

**Issue by AkexStar** [GaryBikini/ChinaAdminDivisonSHP#9]
> 引用
> 推荐引用格式：GaryBikini/ChinaAdminDivisonSHP: v23.01.04, 2023, DOI: [10.5281/zenodo.7503181](https://doi.org/10.5281/zenodo.7503181)

如题，在README.md中提及的DOI地址已无法访问。

---
另外此数据事实上是高德生产的，引用此Repo的DOI是否合适我认为还值得商榷。

**Comment by GaryBikini** [comment]
1. 关于DOI地址，国内访问应该是需要代理
2. 关于是否引用，是可以自由选择的（本项目是在高德地图API获取的结果上进行了一些处理而得到SHP数据，比如修正拓扑错误）

**Comment by AkexStar** [comment]
@GaryBikini 
好的多谢！
确实加上代理可以访问DOI了
